version: 0.2

env:
  parameter-store:
    ACCESS_KEY: slsbotkey
    ACCESS_SECRET_KEY: slsbotsecret

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing Serverless...
      - npm install -g serverless
  pre_build:
    commands:
      - serverless config credentials --provider aws --key $ACCESS_KEY --secret $ACCESS_SECRET_KEY
  build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  post_build:
    commands:
      - sls deploy
